### ISSUE TITLE
Dependancies Conflicts

### ISSUE THREAD

**Issue by izgzhen** [clckwrks/example-dot-org#2]
I tried the "Get Started" tutorial on my machine, and encountered this:

```
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: example-dot-org-0.1.0.0 (user goal)
trying: base-4.7.0.1/installed-df2... (dependency of example-dot-org-0.1.0.0)
trying: happstack-server-7.4.3 (dependency of example-dot-org-0.1.0.0)
next goal: clckwrks-plugin-page (dependency of example-dot-org-0.1.0.0)
rejecting: clckwrks-plugin-page-0.3.6, 0.3.5, 0.3.4 (conflict:
happstack-server==7.4.3, clckwrks-plugin-page => happstack-server>=7.0 &&
<7.4)
rejecting: clckwrks-plugin-page-0.3.3, 0.3.1, 0.3.0 (conflict:
base==4.7.0.1/installed-df2..., clckwrks-plugin-page => base>=4.3 && <4.7)
rejecting: clckwrks-plugin-page-0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1,
0.2.0, 0.1.8, 0.1.5, 0.1.4, 0.1.3, 0.1.2 (conflict: example-dot-org =>
clckwrks-plugin-page>=0.3.0 && <0.4)
Dependency tree exhaustively searched.
```

I am not sure if I change the .cabal file something bad would happen, so I issued this here.

**Comment by stepcut** [comment]
The version of clckwrks on hackage has not been updated to allow happstack-7.4.

This, and a number of other important updates are now in github pending release. I hope to make the release in the next couple of days. The major blocker at the moment is that I am adding all the packages to a continuous build system so that these types of conflicts are visible earlier.
